### ISSUE TITLE
Some stuff :)

### ISSUE THREAD

**Issue by goriunov** [hagsteel/sonr#2]
I have tried replacing `PollOpt::edge()` in `tcp_connection.rs` to `PollOpt::empty()` and seems to give quite a boost to the rps. Not sure why :)

**Comment by hagsteel** [comment]
I suspect that you could write directly to the socket on a local system without waiting for the event to be ready, however if you have a slow connection you might fill up the write buffer until it blocks and it would no longer be possible to write to that connection, thus you would need to wait for an event to trigger the next write, so it's probably not safe to write directly without waiting for `Poll` to notify of a write event with either level or edge triggered `PollOpt`.

Interesting findings though!

I am currently exploring a friendlier interface for Sonr, so just a heads up that the API might change (I also stated this in the README as I don't want people to invest too much time in case the API changes drastically).
Super cool that you are exploring it though!

**Comment by hagsteel** [comment]
Can you share your Node and Rust versions?
Node using libuv should be pretty fast though.

**Comment by goriunov** [comment]
I have rerun test, 
Rust: 1.30.
Node.js: 10.

Test command: `wrk -t4 -c1000 -d10s --latency http://localhost:3000`

Node.js server code: 
```
const http = require("http");
http.createServer(async (req, res) => {
  res.end("<html> <head> <title>An Example Page</title> </head> <body> Hello World, this is a very simple HTML document.  </body> </html>");
}).listen(3000, () => {
  console.log("Server is running");
});;
```

Benchmark results

Rust: 
```
Running 10s test @ http://localhost:3000
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.48ms   88.87ms   1.66s    98.36%
    Req/Sec    12.84k     4.41k   25.15k    63.00%
  Latency Distribution
     50%    2.37ms
     75%    2.80ms
     90%    3.09ms
     99%  255.96ms
  511056 requests in 10.07s, 145.24MB read
  Socket errors: connect 0, read 0, write 0, timeout 68
Requests/sec:  50726.82
Transfer/sec:     14.42MB
```

Node.js: 
```
Running 10s test @ http://localhost:3000
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.22ms   34.99ms 902.01ms   98.92%
    Req/Sec     9.39k     1.51k   13.46k    88.50%
  Latency Distribution
     50%   25.22ms
     75%   26.56ms
     90%   28.24ms
     99%   76.96ms
  373752 requests in 10.05s, 80.91MB read
Requests/sec:  37171.93
Transfer/sec:      8.05MB
```

I know that Node.js is reasonably fast but i would expect that async rust would be at least few times faster like at least at about 100 - 150k, as Go and Node.js have quite a big gap.

**Comment by goriunov** [comment]
Also Rust seems to have a lot of requests with high latency

**Comment by hagsteel** [comment]
@goriunov  sorry I was being unclear: I meant the Rust code you were running.

**Comment by hagsteel** [comment]
Ah right, did you change anything other than the port? (just curious as it's default on 5,000).
I don't know Node's http module or how it works under the hood, but a few remarks:

Isn't Node using libuv with a thread pool?
The example webserver is single threaded.
Since we are talking http here which is stateless there is no need to share data across threads.
running the webserver.rs example in three threads I get the following results:

# Node
```
wrk -c1000 -t4 -d10s --latency http://localhost:3000/
Running 10s test @ http://localhost:3000/
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.33ms   11.86ms 467.92ms   95.67%
    Req/Sec    11.81k     1.70k   14.21k    86.50%
  Latency Distribution
     50%   20.11ms
     75%   21.38ms
     90%   22.79ms
     99%   30.17ms
  470050 requests in 10.07s, 101.76MB read
Requests/sec:  46671.01
Transfer/sec:     10.10MB
```

# Rust
```
wrk -c1000 -t4 -d10s --latency http://localhost:5000/
Running 10s test @ http://localhost:5000/
  4 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.03ms    3.76ms 209.80ms   99.53%
    Req/Sec    33.97k     1.70k   38.12k    69.25%
  Latency Distribution
     50%  700.00us
     75%    1.18ms
     90%    1.92ms
     99%    3.97ms
  1354162 requests in 10.10s, 384.85MB read
Requests/sec: 134138.64
Transfer/sec:     38.12MB
```

However it's important to note that there is a lot of unfairness towards Node here, as the webserver.rs does not parse any headers but simply replies with a hard coded response.

**Comment by goriunov** [comment]
No i did not change anything except of port and no Node js runs on a single thread without threadpool. That is why i was wandering about the performance in the same conditions

**Comment by hagsteel** [comment]
I'm unsure as I really don't know enough about Node, especially the http module.
I'm currently trying to abstract away some boiler plate code, and I want to finish that before I dig into this some more, but any findings you have around this is interesting!

**Comment by hagsteel** [comment]
I think I'll close this for now.
I rewrote the entire library so these numbers don't really apply anymore.
